import { ExternalLink, MoreVertical } from "lucide-react"
import type { AppViewModel } from "@/domain/operations"
import { HealthRow } from "./health-row"
import { StatusBadge } from "./status-badge"

function checkLabel(result: AppViewModel["process"], pass: string) { return result === "pass" ? pass : result === "fail" ? "Failed" : result === "configuration" ? "Not configured" : "Unknown" }
export function AppCard({ app, selected, onSelect, onOpen, onAction }: { app: AppViewModel; selected: boolean; onSelect: () => void; onOpen: () => void; onAction: (action: "start" | "stop" | "restart") => void }) {
  return <article className={`application-card${selected ? " is-selected" : ""}`}><button type="button" className="application-card-select" onClick={onSelect} aria-label={`View details for ${app.displayName}`}><span className="application-icon">{app.displayName.slice(0, 1)}</span><span className="application-identity"><strong className="type-card-title">{app.displayName}</strong><span>{app.hostname ?? "Public address not configured"}</span><code>{app.port ? `Port ${app.port}` : "Port unknown"}</code></span></button><div className="application-card-actions"><StatusBadge status={app.status}/><details className="overflow-menu"><summary aria-label={`More actions for ${app.displayName}`}><MoreVertical size={20}/></summary><div><button onClick={() => onAction("start")}>Start</button><button onClick={() => onAction("stop")}>Stop</button><button onClick={() => onAction("restart")}>Restart</button></div></details></div><div className="application-checks"><HealthRow label="Process" result={app.process} detail={checkLabel(app.process, app.intendedState === "stopped" ? "Stopped" : "Running")}/><HealthRow label="Local app" result={app.local} detail={checkLabel(app.local, app.localLatencyMs ? `${app.localLatencyMs} ms` : "Healthy")}/><HealthRow label="Public access" result={app.public} detail={checkLabel(app.public, "Healthy")}/></div><div className="application-freshness">{app.lastCheckedAt ? `Last checked ${new Date(app.lastCheckedAt).toLocaleString("en-AU", { timeZone: "Australia/Melbourne" })}` : "Awaiting first worker check"}</div><div className="application-buttons"><button type="button" className="guide-button primary" onClick={onOpen} disabled={!app.hostname || app.intendedState === "stopped"}><ExternalLink size={16} aria-hidden="true"/>Open app</button><button type="button" className="guide-button outline" onClick={onSelect}>View details</button></div></article>
}
