import { tokens, type ColourToken, type TypographyRole } from "./tokens"
import { toneStyles } from "./status-styles"

export const typeMetadata: Record<TypographyRole, { label: string; sample: string; purpose: string }> = {
  pageTitle: { label: "Page title", sample: "Style guide", purpose: "Primary page heading" }, panelTitle: { label: "Panel title", sample: "Application details", purpose: "Large contained region" }, cardTitle: { label: "Card title", sample: "Handbook AI", purpose: "Card heading" }, sectionTitle: { label: "Section title", sample: "Recovery", purpose: "Named section" }, body: { label: "Body", sample: "Monitor and manage your applications.", purpose: "Readable content" }, label: { label: "Label", sample: "Auto-recovery", purpose: "Control label" }, caption: { label: "Caption", sample: "Last checked 12 seconds ago", purpose: "Compact metadata" }, data: { label: "Data / Mono", sample: "Port 3001", purpose: "Technical data" }, metric: { label: "Metric", sample: "48 ms", purpose: "Key metric" }, input: { label: "Input", sample: "Application name", purpose: "Editable text" },
}
const purpose: Record<ColourToken, string> = { background: "Page canvas", foreground: "Default text", card: "Card surface", "card-foreground": "Text on cards", popover: "Overlay surface", "popover-foreground": "Text on overlays", primary: "Primary actions", "primary-foreground": "Text on primary", "primary-hover": "Primary hover", secondary: "Secondary surface", "secondary-foreground": "Text on secondary", muted: "Supporting surface", "muted-foreground": "Secondary text", accent: "Selected surface", "accent-foreground": "Selected text", destructive: "Destructive action", "destructive-foreground": "Text on destructive", border: "Dividers", input: "Control boundary", ring: "Focus indicator", sidebar: "Sidebar surface", "sidebar-foreground": "Sidebar text", "sidebar-primary": "Sidebar primary", "sidebar-primary-foreground": "Text on sidebar primary", "sidebar-accent": "Sidebar selected", "sidebar-accent-foreground": "Sidebar selected text", "sidebar-border": "Sidebar divider", "sidebar-ring": "Sidebar focus", success: "Healthy surface", "success-foreground": "Healthy text", "success-border": "Healthy border", warning: "Recovering surface", "warning-foreground": "Recovering text", "warning-border": "Recovering border", danger: "Failure surface", "danger-foreground": "Failure text", "danger-border": "Failure border", info: "Starting surface", "info-foreground": "Starting text", "info-border": "Starting border", neutral: "Neutral surface", "neutral-foreground": "Neutral text", "neutral-border": "Neutral border" }
export const colourRows = (Object.keys(tokens.colours) as ColourToken[]).map((token) => ({ token, value: tokens.colours[token], purpose: purpose[token] }))
export const coreSwatches = ["background", "card", "foreground", "muted", "border", "primary"] as const
export const componentRegistry = ["Sidebar", "Card", "Badge", "Button", "Input", "InputGroup", "Select", "DropdownMenu", "Sheet", "Switch", "Label", "Alert", "AlertDialog", "Dialog", "Field", "Toast", "Tooltip", "Separator", "Skeleton", "Spinner", "Empty", "Table"] as const
export const guideCounts = { typography: Object.keys(tokens.typography).length, palettes: Object.keys(toneStyles).length, colours: Object.keys(tokens.colours).length, components: componentRegistry.length }
export function getTokenExport() { return { schemaVersion: 1, source: "src/design-system/tokens.ts", tokens } }
