import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core"

const timestamps = { createdAt: integer("createdAt", { mode: "timestamp_ms" }).notNull(), updatedAt: integer("updatedAt", { mode: "timestamp_ms" }).notNull() }

export const user = sqliteTable("user", { id: text("id").primaryKey(), name: text("name").notNull(), email: text("email").notNull().unique(), emailVerified: integer("emailVerified", { mode: "boolean" }).notNull().default(false), image: text("image"), ...timestamps })
export const session = sqliteTable("session", { id: text("id").primaryKey(), expiresAt: integer("expiresAt", { mode: "timestamp_ms" }).notNull(), token: text("token").notNull().unique(), createdAt: integer("createdAt", { mode: "timestamp_ms" }).notNull(), updatedAt: integer("updatedAt", { mode: "timestamp_ms" }).notNull(), ipAddress: text("ipAddress"), userAgent: text("userAgent"), userId: text("userId").notNull().references(() => user.id, { onDelete: "cascade" }) }, (t) => [index("session_user_idx").on(t.userId)])
export const account = sqliteTable("account", { id: text("id").primaryKey(), accountId: text("accountId").notNull(), providerId: text("providerId").notNull(), userId: text("userId").notNull().references(() => user.id, { onDelete: "cascade" }), accessToken: text("accessToken"), refreshToken: text("refreshToken"), idToken: text("idToken"), accessTokenExpiresAt: integer("accessTokenExpiresAt", { mode: "timestamp_ms" }), refreshTokenExpiresAt: integer("refreshTokenExpiresAt", { mode: "timestamp_ms" }), scope: text("scope"), password: text("password"), createdAt: integer("createdAt", { mode: "timestamp_ms" }).notNull(), updatedAt: integer("updatedAt", { mode: "timestamp_ms" }).notNull() }, (t) => [index("account_user_idx").on(t.userId)])
export const verification = sqliteTable("verification", { id: text("id").primaryKey(), identifier: text("identifier").notNull(), value: text("value").notNull(), expiresAt: integer("expiresAt", { mode: "timestamp_ms" }).notNull(), createdAt: integer("createdAt", { mode: "timestamp_ms" }).notNull(), updatedAt: integer("updatedAt", { mode: "timestamp_ms" }).notNull() })
export const rateLimit = sqliteTable("rateLimit", { id: text("id").primaryKey(), key: text("key").notNull(), count: integer("count").notNull(), lastRequest: integer("lastRequest", { mode: "timestamp_ms" }).notNull() }, (t) => [uniqueIndex("rate_limit_key_idx").on(t.key)])

export const applications = sqliteTable("applications", { id: text("id").primaryKey(), displayName: text("displayName").notNull(), icon: text("icon").notNull().default("Box"), pm2Name: text("pm2Name").notNull(), pm2Namespace: text("pm2Namespace"), scriptPath: text("scriptPath"), workingDirectory: text("workingDirectory"), processIdentity: text("processIdentity").notNull(), port: integer("port"), portSource: text("portSource"), publicOrigin: text("publicOrigin"), healthPath: text("healthPath").notNull().default("/api/health"), healthMode: text("healthMode").notNull().default("identity"), expectedAppKey: text("expectedAppKey"), connectorId: text("connectorId"), intendedState: text("intendedState").notNull().default("running"), autoRecovery: integer("autoRecovery", { mode: "boolean" }).notNull().default(false), recoveryPausedUntil: integer("recoveryPausedUntil", { mode: "timestamp_ms" }), recipeJson: text("recipeJson"), createdAt: integer("createdAt", { mode: "timestamp_ms" }).notNull(), updatedAt: integer("updatedAt", { mode: "timestamp_ms" }).notNull() }, (t) => [uniqueIndex("applications_identity_idx").on(t.processIdentity), index("applications_name_idx").on(t.displayName)])
export const appStatus = sqliteTable("appStatus", { appId: text("appId").primaryKey().references(() => applications.id, { onDelete: "cascade" }), status: text("status").notNull(), diagnosis: text("diagnosis"), processState: text("processState"), localResult: text("localResult"), publicResult: text("publicResult"), localLatencyMs: integer("localLatencyMs"), publicLatencyMs: integer("publicLatencyMs"), memoryBytes: integer("memoryBytes"), uptimeSince: integer("uptimeSince", { mode: "timestamp_ms" }), lastCheckedAt: integer("lastCheckedAt", { mode: "timestamp_ms" }), localFailureCount: integer("localFailureCount").notNull().default(0), publicFailureCount: integer("publicFailureCount").notNull().default(0), recoveryBlocked: text("recoveryBlocked"), updatedAt: integer("updatedAt", { mode: "timestamp_ms" }).notNull() })
export const healthSamples = sqliteTable("healthSamples", { id: text("id").primaryKey(), appId: text("appId").notNull().references(() => applications.id, { onDelete: "cascade" }), kind: text("kind").notNull(), result: text("result").notNull(), statusCode: integer("statusCode"), latencyMs: integer("latencyMs"), reason: text("reason"), sampledAt: integer("sampledAt", { mode: "timestamp_ms" }).notNull() }, (t) => [index("health_samples_app_idx").on(t.appId, t.sampledAt)])
export const commands = sqliteTable("commands", { id: text("id").primaryKey(), targetType: text("targetType").notNull(), targetId: text("targetId").notNull(), action: text("action").notNull(), state: text("state").notNull().default("queued"), source: text("source").notNull(), idempotencyKey: text("idempotencyKey").notNull(), payloadJson: text("payloadJson"), result: text("result"), expiresAt: integer("expiresAt", { mode: "timestamp_ms" }).notNull(), claimedAt: integer("claimedAt", { mode: "timestamp_ms" }), createdAt: integer("createdAt", { mode: "timestamp_ms" }).notNull(), updatedAt: integer("updatedAt", { mode: "timestamp_ms" }).notNull() }, (t) => [uniqueIndex("commands_dedupe_idx").on(t.idempotencyKey), index("commands_state_idx").on(t.state, t.expiresAt)])
export const activity = sqliteTable("activity", { id: text("id").primaryKey(), appId: text("appId"), connectorId: text("connectorId"), type: text("type").notNull(), severity: text("severity").notNull(), source: text("source").notNull(), summary: text("summary").notNull(), outcome: text("outcome"), createdAt: integer("createdAt", { mode: "timestamp_ms" }).notNull() }, (t) => [index("activity_created_idx").on(t.createdAt)])
export const notifications = sqliteTable("notifications", { id: text("id").primaryKey(), activityId: text("activityId"), title: text("title").notNull(), body: text("body").notNull(), readAt: integer("readAt", { mode: "timestamp_ms" }), createdAt: integer("createdAt", { mode: "timestamp_ms" }).notNull() })
export const workerState = sqliteTable("workerState", { key: text("key").primaryKey(), value: text("value").notNull(), updatedAt: integer("updatedAt", { mode: "timestamp_ms" }).notNull() })

export const schema = { user, session, account, verification, rateLimit, applications, appStatus, healthSamples, commands, activity, notifications, workerState }
