"use client"
import { useState } from "react"
import { Activity, BookOpen, Box, Copy, Download, Menu, Palette, PanelsTopLeft, Settings, Sun } from "lucide-react"
import { tokens } from "@/design-system/tokens"
import { StatusBadge } from "@/components/design-system/status-badge"
import { AppCard } from "@/components/design-system/app-card"
import { colourRows, componentRegistry, coreSwatches, getTokenExport, guideCounts, typeMetadata } from "@/design-system/style-guide-data"

function copy(value: string, done: (message: string) => void) { navigator.clipboard.writeText(value).then(() => done("Copied to clipboard")).catch(() => done("Copy failed — select the value manually")) }
export function StyleGuideClient() {
  const [toast, setToast] = useState(""); const [modal, setModal] = useState<"details" | "dialog" | "confirm" | null>(null); const [name, setName] = useState(""); const [port, setPort] = useState(""); const [recovery, setRecovery] = useState(true); const [loading, setLoading] = useState(false)
  const notice=(message:string)=>{setToast(message); window.setTimeout(()=>setToast(""),2400)}
  const exportTokens=()=>{ const blob=new Blob([JSON.stringify(getTokenExport(),null,2)],{type:"application/json"}); const url=URL.createObjectURL(blob); const a=document.createElement("a"); a.href=url;a.download="operations-blue.tokens.json";a.click();window.setTimeout(()=>URL.revokeObjectURL(url),0);notice("Download started") }
  const invalidName=!name.trim(); const invalidPort=port !== "" && (!/^\d+$/.test(port) || Number(port)<1 || Number(port)>65535)
  return <>
    <div className="portal"><aside className="portal-sidebar"><div className="portal-brand"><strong>Operations</strong><span>Private portal</span></div><nav className="portal-nav" aria-label="Portal navigation"><span><PanelsTopLeft size={20}/>Applications</span><span><Activity size={20}/>Activity</span><span><Settings size={20}/>Settings</span><a href="/style-guide" aria-current="page"><BookOpen size={20}/>Style guide</a></nav></aside><main className="portal-main"><div className="guide">
      <header className="guide-header"><div><h1 className="type-page-title">Style guide</h1><p>Design system for the Operations portal</p></div><div className="guide-actions"><span className="theme-indicator"><Sun size={18} aria-hidden="true"/>Light theme</span><button className="guide-button primary" type="button" onClick={exportTokens}><Download size={18} aria-hidden="true"/>Export tokens</button></div></header>
      <section className="summary-grid" aria-label="Style guide sections"><Summary href="#typeset" icon={<BookOpen/>} title="Typography" description="Text styles and type scale" count={`${guideCounts.typography} text styles`}/><Summary href="#colour-palette" icon={<Palette/>} title="Colours" description="Core and status palettes" count={`${guideCounts.palettes} status palettes`}/><Summary href="#theme-tokens" icon={<Box/>} title="Theme tokens" description="Named interface values" count={`${guideCounts.colours} colour tokens`}/><Summary href="#components" icon={<PanelsTopLeft/>} title="shadcn components" description="Shared UI building blocks" count={`${guideCounts.components} components`}/></section>
      <div className="foundation-grid"><section className="guide-card" id="typeset"><h2 className="type-section-title">Typeset</h2><p>Geist for interface text; Geist Mono for technical data.</p>{Object.entries(typeMetadata).map(([role, meta])=>{const style=tokens.typography[role as keyof typeof tokens.typography];return <div className="type-row" key={role}><div><strong>{meta.label}</strong><small>{meta.purpose}</small></div><div><div className={`type-${role.replace(/[A-Z]/g,m=>`-${m.toLowerCase()}`)}`}>{meta.sample}</div><div className="type-note">{style.size} / {style.lineHeight} / {style.weight}</div></div></div>})}</section>
        <section className="guide-card" id="colour-palette"><h2 className="type-section-title">Colour palette</h2><p>Core UI colours and semantic status pairs.</p><h3>Core UI</h3><div className="swatches">{coreSwatches.map((key)=><Swatch key={key} name={key} value={tokens.colours[key]} notice={notice}/>)}</div><h3>Status colours</h3><div className="swatches">{(["success","warning","danger","info","neutral"] as const).map((tone)=><Swatch key={tone} name={tone} value={tokens.colours[tone]} notice={notice}/>)}</div></section>
        <section className="guide-card token-card" id="theme-tokens"><h2 className="type-section-title">Theme tokens</h2><p>Key semantic colour tokens and their mapped values.</p><div className="token-region" tabIndex={0} aria-label="Theme token reference"><table><thead><tr><th>Token</th><th>Value</th><th>Used for</th><th><span className="sr-only">Copy</span></th></tr></thead><tbody>{colourRows.map(row=><tr key={row.token}><td><code>{row.token}</code></td><td><span className="token-value"><i className="dot" style={{backgroundColor:row.value}}/>{row.value}</span></td><td>{row.purpose}</td><td><button className="copy-button" aria-label={`Copy var(--${row.token})`} onClick={()=>copy(`var(--${row.token})`,notice)}><Copy size={14}/></button></td></tr>)}</tbody></table></div></section></div>
      <div className="section-stack"><section className="guide-card" id="components"><h2 className="type-section-title">shadcn components</h2><p>Interactive examples only. No application settings are changed.</p><div className="component-grid">{componentRegistry.map((item)=><div className="component-tile" key={item}><div className="component-preview">{preview(item, {setModal, notice, recovery, setRecovery})}</div><strong>{item}</strong></div>)}</div></section>
      <section className="guide-card" id="status-badges"><h2 className="type-section-title">Status badges</h2><p>Application-state examples used across the portal.</p><div className="status-list">{["healthy","recovering","starting","failed","public-unavailable","stopped","unknown"].map(status=><StatusBadge key={status} status={status}/>)}</div></section>
      <section className="guide-card" id="buttons-fields"><h2 className="type-section-title">Buttons & fields</h2><p>Common form elements, validation and disabled/loading states.</p><div className="field-row"><label>Application name<input className="input" value={name} onChange={e=>setName(e.target.value)} aria-invalid={invalidName}/>{invalidName&&<span className="error">Application name is required.</span>}</label><label>Port<input className="input" value={port} onChange={e=>setPort(e.target.value)} aria-invalid={invalidPort} inputMode="numeric" placeholder="1–65535"/>{invalidPort&&<span className="error">Use a port from 1 to 65535.</span>}</label><select aria-label="Demo status"><option>Healthy</option><option>Recovering</option><option>Needs attention</option></select><div className="button-row"><button type="button" className="guide-button primary" disabled={loading} onClick={()=>{setLoading(true);window.setTimeout(()=>{setLoading(false);notice("Demo action complete")},700)}}>{loading?"Checking…":"Primary button"}</button><button type="button" className="guide-button outline">Outline button</button><button type="button" className="guide-button ghost">Ghost button</button><button type="button" className="guide-button" disabled>Disabled</button></div></div></section>
      <section className="guide-card" id="spacing-shape"><h2 className="type-section-title">Spacing & shape</h2><p>Shared spacing, 44px controls, radii, focus and reduced-motion rules.</p><div className="ruler">{[4,8,12,16,24,32].map((height)=><span key={height} style={{height}} title={`${height}px`}/>)}</div><div className="button-row"><button className="guide-button primary" type="button">44px control</button><span className="badge status-neutral">8px corners</span><span className="badge status-info">2px focus ring</span></div></section>
      <section className="guide-card" id="application-example"><h2 className="type-section-title">Application example</h2><p>Reusable application card with independently modelled checks.</p><div className="foundation-grid"><AppCard app={{id:"guide-app",displayName:"Handbook AI",icon:"BookOpen",pm2Name:"handbook",hostname:"handbook.internal.example",port:3001,intendedState:"running",autoRecovery:false,recoveryPausedUntil:null,status:"public-unavailable",diagnosis:null,process:"pass",local:"pass",public:"fail",localLatencyMs:48,memoryBytes:null,uptimeSince:null,lastCheckedAt:new Date().toISOString(),localFailureCount:0,publicFailureCount:1,recoveryBlocked:null}} selected={false} onSelect={()=>setModal("details")} onOpen={()=>notice("Demo open-app action")} onAction={()=>notice("Demo command queued")}/><AppCard app={{id:"guide-unknown-port",displayName:"Unknown port",icon:"Box",pm2Name:"unknown",hostname:null,port:null,intendedState:"running",autoRecovery:false,recoveryPausedUntil:null,status:"unknown",diagnosis:null,process:"unknown",local:"unknown",public:"unknown",localLatencyMs:null,memoryBytes:null,uptimeSince:null,lastCheckedAt:null,localFailureCount:0,publicFailureCount:0,recoveryBlocked:null}} selected={false} onSelect={()=>setModal("details")} onOpen={()=>notice("No configured public URL")} onAction={()=>notice("Demo command queued")}/></div></section></div>
    </div></main></div>
    {modal&&<div className="modal-backdrop" role="presentation"><div className="modal" role="dialog" aria-modal="true" aria-labelledby="demo-title"><h2 id="demo-title" className="type-card-title">{modal === "confirm" ? "Restart application?" : modal === "dialog" ? "Demo application form" : "Handbook AI details"}</h2><p className="type-body">{modal === "confirm" ? "Demo only. No application or tunnel will be restarted." : "This is a local demonstration with no persistent changes."}</p><button className="guide-button primary" type="button" onClick={()=>{setModal(null);notice("Demo closed")}}>Close</button></div></div>}{toast&&<div className="toast" role="status">{toast}</div>}</>
}
function Summary({href,icon,title,description,count}:{href:string;icon:React.ReactNode;title:string;description:string;count:string}){return <a className="summary-card" href={href}><span className="summary-icon">{icon}</span><strong>{title}</strong><span>{description}</span><em className="count">{count}</em></a>}
function Swatch({name,value,notice}:{name:string;value:string;notice:(s:string)=>void}){return <button className="swatch" onClick={()=>copy(value,notice)} aria-label={`Copy ${name}, ${value}`}><span className="swatch-color" style={{backgroundColor:value}}/><strong>{name}</strong><small>{value}</small></button>}
function preview(item:string, api:{setModal:(v:"details"|"dialog"|"confirm")=>void;notice:(s:string)=>void;recovery:boolean;setRecovery:(v:boolean)=>void}) { if(item==="Button")return <button className="guide-button primary" type="button">Button</button>; if(item==="Input"||item==="InputGroup")return <input className="input" aria-label={`${item} demo`} placeholder="Enter text…"/>; if(item==="Select")return <select aria-label="Select demo"><option>Select option</option></select>; if(item==="Badge")return <StatusBadge status="healthy"/>; if(item==="Switch")return <label><input type="checkbox" checked={api.recovery} onChange={e=>api.setRecovery(e.target.checked)}/> Auto-recovery</label>; if(item==="Alert")return <span className="badge status-danger">Needs attention</span>; if(item==="Dialog")return <button className="guide-button outline" type="button" onClick={()=>api.setModal("dialog")}>Open dialog</button>; if(item==="AlertDialog")return <button className="guide-button outline" type="button" onClick={()=>api.setModal("confirm")}>Confirm restart</button>; if(item==="Sheet")return <button className="guide-button outline" type="button" onClick={()=>api.setModal("details")}>View details</button>; if(item==="Toast")return <button className="guide-button outline" type="button" onClick={()=>api.notice("Notification shown")}>Notify</button>; if(item==="Tooltip")return <button className="guide-button outline" type="button" title="Helpful context">Hover</button>; if(item==="Skeleton")return <span style={{width:"100%",height:"1rem",background:"var(--muted)",borderRadius:"var(--radius-sm)"}}/>; if(item==="Spinner")return <span className="animate-spin">◌</span>; if(item==="Separator")return <hr style={{width:"100%"}}/>; if(item==="Empty")return <span>No records</span>; if(item==="Table")return <span>Token table</span>; if(item==="Sidebar")return <Menu/>; if(item==="Card")return <span className="badge status-neutral">Card surface</span>; if(item==="DropdownMenu")return <button className="guide-button outline" type="button" onClick={()=>api.notice("Demo menu action")}>Menu</button>; if(item==="Field")return <label>Label</label>; if(item==="Label")return <label>Application name</label>; return null }
