import { writeFile, readFile } from "node:fs/promises"
import { resolve } from "node:path"
import { pathToFileURL } from "node:url"
import { tokens } from "../src/design-system/tokens.ts"

const kebab = (value: string) => value.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)
export function renderTheme() {
  const colourVars = Object.entries(tokens.colours).map(([key, value]) => `  --${key}: ${value};\n  --color-${key}: var(--${key});`).join("\n")
  const fontVars = Object.entries(tokens.fonts).map(([key, value]) => `  --ds-font-${key}: ${value};`).join("\n")
    + "\n" + Object.entries(tokens.spacing).map(([key, value]) => `  --space-${kebab(key)}: ${value};`).join("\n")
    + `\n  --card-padding: ${tokens.layout.cardPadding.mobile};\n  --details-width: ${tokens.layout.detailsWidth};\n  --panel-padding: ${tokens.layout.panelPadding};\n  --shadow-overlay: ${tokens.shadows.overlay};`
  const typeVars = Object.entries(tokens.typography).map(([key, value]) => `  --type-${kebab(key)}-size: ${value.size};\n  --type-${kebab(key)}-line: ${value.lineHeight};\n  --type-${kebab(key)}-weight: ${value.weight};\n  --type-${kebab(key)}-tracking: ${value.tracking};`).join("\n")
  const utilities = Object.entries(tokens.typography).map(([key, value]) => { const name=kebab(key); const style = value as import("../src/design-system/tokens.ts").TypeStyle; return `@utility type-${name} { font-family: var(--ds-font-${style.family}); font-size: var(--type-${name}-size); line-height: var(--type-${name}-line); font-weight: var(--type-${name}-weight); letter-spacing: var(--type-${name}-tracking);${style.tabular ? " font-variant-numeric: tabular-nums;" : ""} }` }).join("\n")
  return `/* This file is generated by scripts/generate-theme.ts. Do not hand-edit. */\n:root {\n${colourVars}\n${fontVars}\n${typeVars}\n  --radius: ${tokens.radius.lg}; --radius-sm: ${tokens.radius.sm}; --radius-md: ${tokens.radius.md}; --radius-lg: ${tokens.radius.lg}; --radius-xl: ${tokens.radius.xl}; --radius-2xl: ${tokens.radius["2xl"]};\n  --control-height: ${tokens.sizing.controlHeight}; --sidebar-width: ${tokens.layout.sidebarWidth}; --guide-token-table-height: ${tokens.layout.styleGuideTokenTableMaxHeight}; --page-padding: ${tokens.layout.pagePadding.mobile}; --grid-gap: ${tokens.layout.gridGap.mobile};\n}\n@media (min-width: ${tokens.breakpoints.tablet}) { :root { --page-padding: ${tokens.layout.pagePadding.tablet}; --grid-gap: ${tokens.layout.gridGap.desktop}; --type-page-title-size: ${tokens.typography.pageTitle.size}; --type-page-title-line: ${tokens.typography.pageTitle.lineHeight}; } }\n@media (min-width: ${tokens.breakpoints.desktop}) { :root { --page-padding: ${tokens.layout.pagePadding.desktop}; } }\n${utilities}\n`
}
export async function isThemeCurrent(output: string) {
  return await readFile(output, "utf8").catch(() => "") === renderTheme()
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  const output = resolve(import.meta.dirname, "../src/design-system/theme.generated.css")
  if (process.argv.includes("--check")) {
    if (!await isThemeCurrent(output)) { console.error("theme.generated.css is missing or stale"); process.exitCode = 1 }
  } else await writeFile(output, renderTheme())
}
